### PR TITLE
I add two app consumer and producer

### PR DESCRIPTION
**Pull request by tech-takumis**
And consumer na consumer mao nang app2 and producer mao nalang app1 nag create ko diha og app.

### CODE REVIEW

**Comment by tech-takumis** [comment]
pwede sa app1 is pag buhat mo og user og transaction na model guys

**Comment by ayingleoneilivan** [comment]
sige sige

**Comment by TheLerm0xThe0ry** [comment]
Collaborating with them right now.

**Comment by MarryJoyBersabal** [comment]
cge paul

**Pull request merged**
